// Offline cache for the Drift & Bloom web app. Generated by tools/build_site.py.
const CORE = 'drift-and-bloom-core-a570a77f8333';
const ASSETS = 'drift-and-bloom-assets-19f5c8d9c55d';
const CORE_FILES = [
  "./",
  "index.html",
  "workspace/character/spirit_draw.js",
  "workspace/character/scene_draw.js",
  "assets/sprites/dragon_sheet.png",
  "assets/levels/stages.json",
  "worlds/alien.js",
  "worlds/animal.js",
  "worlds/hell.js",
  "worlds/world_core.js",
  "manifest.webmanifest",
  "icons/icon-180.png",
  "icons/icon-192.png",
  "icons/icon-512.png"
];
const ASSET_FILES = [
  "assets/worlds/alien/boss.png",
  "assets/worlds/alien/fighter.png",
  "assets/worlds/alien/fighter2.png",
  "assets/worlds/alien/interceptor.png",
  "assets/worlds/alien/jupiter.png",
  "assets/worlds/alien/ship_player.png",
  "assets/worlds/alien/space_backdrop.jpg",
  "assets/worlds/animal/bark.webp",
  "assets/worlds/animal/bg_far.webp",
  "assets/worlds/animal/bg_mid.webp",
  "assets/worlds/animal/boar.webp",
  "assets/worlds/animal/croc.webp",
  "assets/worlds/animal/eagle.webp",
  "assets/worlds/animal/fern.webp",
  "assets/worlds/animal/litter.webp",
  "assets/worlds/animal/lotus.webp",
  "assets/worlds/animal/python.webp",
  "assets/worlds/animal/vulture.webp",
  "assets/worlds/CREDITS.json",
  "assets/worlds/hell/backdrop.jpg",
  "assets/worlds/hell/bat.png",
  "assets/worlds/hell/bat_glow.png",
  "assets/worlds/hell/canyon.jpg",
  "assets/worlds/hell/demon.png",
  "assets/worlds/hell/demon_glow.png",
  "assets/worlds/hell/gargoyle.png",
  "assets/worlds/hell/gargoyle_glow.png",
  "assets/worlds/hell/ghoul.png",
  "assets/worlds/hell/ghoul_glow.png",
  "assets/worlds/hell/hellhound.png",
  "assets/worlds/hell/hellhound_glow.png",
  "assets/worlds/hell/hornhound.png",
  "assets/worlds/hell/hornhound_glow.png",
  "assets/worlds/hell/imp.png",
  "assets/worlds/hell/imp_glow.png",
  "assets/worlds/hell/rock.jpg",
  "assets/worlds/hell/volcano.jpg",
  "assets/hero/ash/hero.json",
  "assets/hero/ash/hero_0.webp",
  "assets/hero/ash/hero_1.webp",
  "assets/hero/ash/portrait.webp",
  "assets/hero/brann/hero.json",
  "assets/hero/brann/hero_0.webp",
  "assets/hero/brann/hero_1.webp",
  "assets/hero/brann/portrait.webp",
  "assets/hero/darius/hero.json",
  "assets/hero/darius/hero_0.webp",
  "assets/hero/darius/hero_1.webp",
  "assets/hero/darius/portrait.webp",
  "assets/hero/kael/hero.json",
  "assets/hero/kael/hero_0.webp",
  "assets/hero/kael/hero_1.webp",
  "assets/hero/kael/portrait.webp",
  "assets/hero/lyra/hero.json",
  "assets/hero/lyra/hero_0.webp",
  "assets/hero/lyra/hero_1.webp",
  "assets/hero/lyra/portrait.webp",
  "assets/hero/mira/hero.json",
  "assets/hero/mira/hero_0.webp",
  "assets/hero/mira/hero_1.webp",
  "assets/hero/mira/portrait.webp",
  "assets/hero/roster.json",
  "assets/hero/rowan/hero.json",
  "assets/hero/rowan/hero_0.webp",
  "assets/hero/rowan/hero_1.webp",
  "assets/hero/rowan/portrait.webp",
  "assets/hero/sera/hero.json",
  "assets/hero/sera/hero_0.webp",
  "assets/hero/sera/hero_1.webp",
  "assets/hero/sera/hero_2.webp",
  "assets/hero/sera/portrait.webp",
  "assets/hero/vex/hero.json",
  "assets/hero/vex/hero_0.webp",
  "assets/hero/vex/hero_1.webp",
  "assets/hero/vex/portrait.webp",
  "assets/hero/wren/hero.json",
  "assets/hero/wren/hero_0.webp",
  "assets/hero/wren/hero_1.webp",
  "assets/hero/wren/portrait.webp"
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CORE)
    .then(c => c.addAll(CORE_FILES.map(f => new Request(f, { cache: 'reload' }))))
    .then(() => self.skipWaiting()));
});

// a new version replaces the old caches; the running game keeps going, the next launch is new
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys
      .filter(k => k.startsWith('drift-and-bloom-') && k !== CORE && k !== ASSETS)
      .map(k => caches.delete(k))))
    .then(() => self.clients.claim())
    .then(() => {
      // world art: fetch in the background so the worlds also work offline later
      caches.open(ASSETS).then(c => ASSET_FILES.reduce((p, f) => p.then(() =>
        c.match(f).then(hit => hit || fetch(f, { cache: 'reload' }).then(r => r.ok && c.put(f, r)).catch(() => {}))
      ), Promise.resolve()));
    }));
});

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET' || new URL(e.request.url).origin !== location.origin) return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then(hit => hit || fetch(e.request).then(r => {
    // anything not cached yet (world art on first use) is kept for next time
    if (r.ok) { const copy = r.clone(); caches.open(ASSETS).then(c => c.put(e.request, copy)); }
    return r;
  })));
});
