// Offline cache for the Drift & Bloom web app. Generated by tools/build_site.py.
const CACHE = 'drift-and-bloom-9a5a69ecd8f1';
const FILES = [
  "./",
  "index.html",
  "workspace/character/spirit_draw.js",
  "workspace/character/scene_draw.js",
  "assets/sprites/dragon_sheet.png",
  "assets/levels/stages.json",
  "manifest.webmanifest",
  "icons/icon-180.png",
  "icons/icon-192.png",
  "icons/icon-512.png"
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE)
    .then(c => c.addAll(FILES.map(f => new Request(f, { cache: 'reload' }))))
    .then(() => self.skipWaiting()));
});

// a new version replaces the old cache; the running game keeps going, the next launch is new
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys
      .filter(k => k.startsWith('drift-and-bloom-') && k !== CACHE)
      .map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  e.respondWith(caches.open(CACHE)
    .then(c => c.match(e.request, { ignoreSearch: true }))
    .then(hit => hit || fetch(e.request)));
});
