"""Builds the public web version of Drift & Bloom from the game's working folder.

    python tools/build_site.py [path/to/DriftAndBloom]

Copies the game files in, writes index.html (game.html plus the tags that make
it installable with "Add to Home Screen") and sw.js (the offline cache, stamped
with a hash of every file so phones pick up a new version on their next launch).
"""
import hashlib
import json
import pathlib
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else r"C:\Users\test\Downloads\DriftAndBloom")

# everything game.html loads, at the same relative paths
GAME_FILES = [
    "workspace/character/spirit_draw.js",
    "workspace/character/scene_draw.js",
    "assets/sprites/dragon_sheet.png",
    "assets/levels/stages.json",
]
WEB_FILES = [
    "manifest.webmanifest",
    "icons/icon-180.png",
    "icons/icon-192.png",
    "icons/icon-512.png",
]

HEAD = """<!-- web app: installable from Safari / Chrome, plays offline -->
<link rel="manifest" href="manifest.webmanifest">
<link rel="apple-touch-icon" href="icons/icon-180.png">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="Drift &amp; Bloom">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="theme-color" content="#040e18">
<script>
if ('serviceWorker' in navigator) {
  addEventListener('load', function () { navigator.serviceWorker.register('sw.js'); });
}
</script>
"""

SW = """// Offline cache for the Drift & Bloom web app. Generated by tools/build_site.py.
const CACHE = 'drift-and-bloom-__VERSION__';
const FILES = __FILES__;

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE)
    .then(c => c.addAll(FILES.map(f => new Request(f, { cache: 'reload' }))))
    .then(() => self.skipWaiting()));
});

// a new version replaces the old cache; the running game keeps going, the next launch is new
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys
      .filter(k => k.startsWith('drift-and-bloom-') && k !== CACHE)
      .map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  e.respondWith(caches.open(CACHE)
    .then(c => c.match(e.request, { ignoreSearch: true }))
    .then(hit => hit || fetch(e.request)));
});
"""


def write(path, text):
    with open(ROOT / path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def main():
    for f in GAME_FILES:
        dst = ROOT / f
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(SRC / f, dst)

    html = (SRC / "game.html").read_text(encoding="utf-8")
    if "</head>" not in html:
        sys.exit("game.html has no </head>")
    write("index.html", html.replace("</head>", HEAD + "</head>", 1))

    digest = hashlib.sha256()
    for f in ["index.html"] + GAME_FILES + WEB_FILES:
        digest.update((ROOT / f).read_bytes())
    version = digest.hexdigest()[:12]
    files = ["./", "index.html"] + GAME_FILES + WEB_FILES
    write("sw.js", SW.replace("__VERSION__", version).replace("__FILES__", json.dumps(files, indent=2)))

    unlocked = "const UNLOCK_ALL = true;" in html
    print(f"built version {version} from {SRC}  (all levels unlocked: {unlocked})")


if __name__ == "__main__":
    main()
