"""Builds the public web version of Drift & Bloom from the game's working folder.

    python tools/build_site.py [path/to/DriftAndBloom]

Copies the game files in, writes index.html (game.html plus the tags that make
it installable with "Add to Home Screen") and sw.js (the offline cache). The
cache comes in two parts, each stamped with a hash of its files:
  core   — the game itself, cached when the web app installs
  assets — the side worlds' art, cached in the background and on first use,
           so a game-only update doesn't re-download every image
"""
import hashlib
import json
import pathlib
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else r"C:\Users\test\Downloads\DriftAndBloom")

# everything game.html loads, at the same relative paths
GAME_FILES = [
    "workspace/character/spirit_draw.js",
    "workspace/character/scene_draw.js",
    "assets/sprites/dragon_sheet.png",
    "assets/levels/stages.json",
]
WEB_FILES = [
    "manifest.webmanifest",
    "icons/icon-180.png",
    "icons/icon-192.png",
    "icons/icon-512.png",
]
ASSET_TYPES = {".png", ".webp", ".jpg", ".json", ".mp3"}

HEAD = """<!-- web app: installable from Safari / Chrome, plays offline -->
<link rel="manifest" href="manifest.webmanifest">
<link rel="apple-touch-icon" href="icons/icon-180.png">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="Drift &amp; Bloom">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="theme-color" content="#040e18">
<script>
if ('serviceWorker' in navigator) {
  addEventListener('load', function () { navigator.serviceWorker.register('sw.js'); });
}
</script>
"""

SW = """// Offline cache for the Drift & Bloom web app. Generated by tools/build_site.py.
const CORE = 'drift-and-bloom-core-__CORE_V__';
const ASSETS = 'drift-and-bloom-assets-__ASSET_V__';
const CORE_FILES = __CORE__;
const ASSET_FILES = __ASSETS__;

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CORE)
    .then(c => c.addAll(CORE_FILES.map(f => new Request(f, { cache: 'reload' }))))
    .then(() => self.skipWaiting()));
});

// a new version replaces the old caches; the running game keeps going, the next launch is new
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys
      .filter(k => k.startsWith('drift-and-bloom-') && k !== CORE && k !== ASSETS)
      .map(k => caches.delete(k))))
    .then(() => self.clients.claim())
    .then(() => {
      // world art: fetch in the background so the worlds also work offline later
      caches.open(ASSETS).then(c => ASSET_FILES.reduce((p, f) => p.then(() =>
        c.match(f).then(hit => hit || fetch(f, { cache: 'reload' }).then(r => r.ok && c.put(f, r)).catch(() => {}))
      ), Promise.resolve()));
    }));
});

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET' || new URL(e.request.url).origin !== location.origin) return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then(hit => hit || fetch(e.request).then(r => {
    // anything not cached yet (world art on first use) is kept for next time
    if (r.ok) { const copy = r.clone(); caches.open(ASSETS).then(c => c.put(e.request, copy)); }
    return r;
  })));
});
"""


def write(path, text):
    with open(ROOT / path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def digest(files):
    h = hashlib.sha256()
    for f in files:
        h.update(f.encode())
        h.update((ROOT / f).read_bytes())
    return h.hexdigest()[:12]


def main():
    for f in GAME_FILES:
        dst = ROOT / f
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(SRC / f, dst)

    # side worlds: engine + modules, and their shipped art (never the raw src/ downloads)
    for d in ("worlds", "assets/worlds"):
        if (ROOT / d).exists():
            shutil.rmtree(ROOT / d)
    world_js = []
    for f in sorted((SRC / "worlds").glob("*.js")):
        rel = f"worlds/{f.name}"
        (ROOT / "worlds").mkdir(exist_ok=True)
        shutil.copyfile(f, ROOT / rel)
        world_js.append(rel)
    assets = []
    if (SRC / "assets/worlds").exists():
        for f in sorted((SRC / "assets/worlds").rglob("*")):
            if f.is_file() and f.suffix.lower() in ASSET_TYPES and "src" not in f.relative_to(SRC).parts:
                rel = f.relative_to(SRC).as_posix()
                (ROOT / rel).parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(f, ROOT / rel)
                assets.append(rel)

    # the heroes: CC0 sprite sheets (Quaternius characters + animations, KayKit weapons,
    # Mesh2Motion bow moves) in assets/hero/<id>/ + roster.json. The old Yasuo sets ('day',
    # 'hell') were private-only and must never be published.
    if (ROOT / "assets/hero").exists():
        shutil.rmtree(ROOT / "assets/hero")
    hero_src = SRC / "assets/hero"
    for bad in ("day", "hell"):
        if (hero_src / bad).exists():
            sys.exit(f"refusing to publish: assets/hero/{bad} (old private hero set) is still in the working folder")
    for f in sorted(hero_src.rglob("*")) if hero_src.exists() else []:
        if f.is_file() and f.suffix.lower() in (".webp", ".json"):
            rel = f.relative_to(SRC).as_posix()
            (ROOT / rel).parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(f, ROOT / rel)
            assets.append(rel)
    html = (SRC / "game.html").read_text(encoding="utf-8")
    if "</head>" not in html:
        sys.exit("game.html has no </head>")
    write("index.html", html.replace("</head>", HEAD + "</head>", 1))

    core = ["index.html"] + GAME_FILES + world_js + WEB_FILES
    # hero sprite sheets (~1.5 MB per hero) are cached when a hero is first picked, not all up front
    # music (~1-2 MB a track) too: each track is cached the first time it plays
    background = [a for a in assets if not (a.startswith("assets/hero/") and "/hero_" in a and a.endswith(".webp"))
                  and not a.startswith("assets/worlds/audio/music_")]
    sw = (SW.replace("__CORE_V__", digest(core)).replace("__ASSET_V__", digest(assets) if assets else "none")
            .replace("__CORE__", json.dumps(["./"] + core, indent=2)).replace("__ASSETS__", json.dumps(background, indent=2)))
    write("sw.js", sw)

    size = sum((ROOT / f).stat().st_size for f in assets) / 1e6
    unlocked = "const UNLOCK_ALL = true;" in html
    print(f"built: {len(world_js)} world modules, {len(assets)} world assets ({size:.1f} MB)  (all levels unlocked: {unlocked})")


if __name__ == "__main__":
    main()
